apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: goods
spec:
  parentRefs:
  - group: ""
    kind: Service
    name: goods-service
  rules:
  - matches:
    - headers:
      - type: RegularExpression
        name: baggage
        value: .*swimlane=dev-feature1.*
    backendRefs:
    - name: goods-service-dev-feature1
      port: 50051
  - matches:
    - headers:
      - type: RegularExpression
        name: baggage
        value: .*swimlane=dev-feature2.*
    backendRefs:
    - name: goods-service-dev-feature2
      port: 50051
  - backendRefs:
    - name: goods-service-main
      port: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: goods-service-main
spec:
  selector:
    app: goods
    swimlane: main
  ports:
    - protocol: TCP
      port: 50051
      targetPort: goods-port

---
apiVersion: v1
kind: Service
metadata:
  name: goods-service-dev-feature1
spec:
  selector:
    app: goods
    swimlane: dev-feature1
  ports:
    - protocol: TCP
      port: 50051
      targetPort: goods-port

---
apiVersion: v1
kind: Service
metadata:
  name: goods-service-dev-feature2
spec:
  selector:
    app: goods
    swimlane: dev-feature2
  ports:
    - protocol: TCP
      port: 50051
      targetPort: goods-port
